### ISSUE TITLE
Glyph sources have bad composites

### ISSUE THREAD

**Issue by m4rc1e** [Omnibus-Type/Sansita#1]
![screen shot 2018-07-03 at 14 52 54](https://user-images.githubusercontent.com/7525512/42223913-ce07979a-7ed0-11e8-9567-16701184b629.png)

Exists in GF versions as well:

![screen shot 2018-07-03 at 14 53 39](https://user-images.githubusercontent.com/7525512/42223952-e89404d6-7ed0-11e8-9463-e04b25b06eed.png)

@davelab6 we should get this fixed asap.

**Comment by davelab6** [comment]
I agree, but I hope that @Omnibus-Type folks can provide the fix in a new release, and you can use your tools to prepare a PR. The GF team won't be able to ship this until last week of July at the earliest, though.

**Comment by m4rc1e** [comment]
@davelab6 Done it. will push an update with the VFs

**Comment by m4rc1e** [comment]
![desktop_windows_7_ie_9 0_](https://user-images.githubusercontent.com/7525512/42225991-c2a20372-7ed5-11e8-968b-16ee9da98c01.gif)

**Comment by davelab6** [comment]
Even better :D
